'use client';
/* oxlint-disable jsx-a11y/control-has-associated-label, jsx-a11y/label-has-associated-control, jsx-a11y/img-redundant-alt, jsx-a11y/media-has-caption, next/no-img-element */

import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, Camera, Check, ChevronRight, Clock3, Eye, FileImage, Gauge, HelpCircle, History, Home, Info, LogOut, Menu, ScanLine, Settings, ShieldCheck, Sparkles, Upload, User, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Progress } from '@/components/ui/progress';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

type View = 'landing'|'login'|'signup'|'dashboard'|'new'|'camera'|'processing'|'result'|'history'|'details'|'settings';
const screenings = [
  {id:'DRS-240831-03', patient:'Anonymous patient', date:'Today, 10:24', grade:'Moderate NPDR', risk:'Elevated', confidence:87},
  {id:'DRS-240830-08', patient:'Anonymous patient', date:'Yesterday, 16:42', grade:'No DR', risk:'Low', confidence:92},
  {id:'DRS-240828-04', patient:'Anonymous patient', date:'28 Aug, 11:08', grade:'Mild NPDR', risk:'Monitor', confidence:81},
];

function Logo(){return <div className="flex items-center gap-3 font-semibold tracking-tight"><span className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground"><Eye size={21}/></span><span>Drishti<span className="text-primary">AI</span></span></div>}

export default function App(){
  const [view,setView]=useState<View>('landing'); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState(''); const [error,setError]=useState(''); const [menu,setMenu]=useState(false);
  const go=(next:View)=>{setView(next);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})};
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  const choose=(f?:File)=>{setError(''); if(!f)return; if(!['image/jpeg','image/png'].includes(f.type)){setError('Please choose a JPG or PNG retinal image.');return} if(f.size>10*1024*1024){setError('Image must be 10 MB or smaller.');return} setFile(f);setPreview(URL.createObjectURL(f))};
  if(view==='landing')return <Landing go={go}/>;
  if(view==='login'||view==='signup')return <Auth mode={view} go={go}/>;
  return <Shell view={view} go={go} menu={menu} setMenu={setMenu}>
    {view==='dashboard'&&<Dashboard go={go}/>} {view==='new'&&<NewScreening go={go} choose={choose} file={file} preview={preview} error={error}/>} {view==='camera'&&<CameraCapture go={go}/>} {view==='processing'&&<Processing go={go}/>} {(view==='result'||view==='details')&&<Result go={go} preview={preview}/>} {view==='history'&&<HistoryPage go={go}/>} {view==='settings'&&<SettingsPage/>}
  </Shell>;
}

function Landing({go}:{go:(v:View)=>void}){return <main className="min-h-screen bg-background text-foreground"><header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10"><Logo/><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#how">How it works</a><a href="#safety">Safety</a><a href="#about">About</a></nav><Button variant="outline" className="rounded-xl" onClick={()=>go('login')}>Sign in</Button></header><section className="mx-auto grid max-w-7xl gap-12 px-6 pb-20 pt-14 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:px-10 lg:pt-20"><div><Badge variant="secondary" className="mb-6 rounded-full px-3 py-1 text-primary"><Sparkles className="mr-1 size-3.5"/> Explainable screening support</Badge><h1 className="max-w-3xl text-5xl font-semibold leading-[1.06] tracking-[-.045em] sm:text-6xl">Retinal screening insights you can understand.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">A transparent, guided workflow for reviewing retinal images—showing what the system noticed and why it matters.</p><div className="mt-9 flex flex-wrap gap-3"><Button size="lg" className="h-12 rounded-xl px-6" onClick={()=>go('signup')}>Get started <ArrowRight className="ml-2 size-4"/></Button><Button size="lg" variant="outline" className="h-12 rounded-xl px-6" onClick={()=>go('login')}>View demo</Button></div><p className="mt-5 flex items-center gap-2 text-sm text-muted-foreground"><ShieldCheck className="size-4 text-primary"/> Screening support only—not a medical diagnosis.</p></div><ResultCard compact/></section><section id="how" className="border-y bg-white"><div className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><p className="eyebrow">A careful workflow</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">From image to understandable next step</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[[Upload,'Capture','Upload or capture a clear retinal fundus image.'],[ScanLine,'Review','Image quality and retina visibility are checked.'],[Gauge,'Understand','See demo severity, confidence, and highlighted regions.']].map(([I,t,d],i)=>{const Icon=I as typeof Upload;return <div key={String(t)} className="rounded-2xl border p-6"><span className="grid size-11 place-items-center rounded-xl bg-secondary text-primary"><Icon/></span><p className="mt-5 text-sm text-primary">0{i+1}</p><h3 className="mt-1 font-semibold">{String(t)}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{String(d)}</p></div>})}</div></div></section><footer id="safety" className="mx-auto max-w-7xl px-6 py-12 text-sm text-muted-foreground lg:px-10"><div className="flex flex-col justify-between gap-6 md:flex-row"><Logo/><p className="max-w-xl">DrishtiAI is a research and demonstration decision-support application. Demo outputs are simulated and must not be used for diagnosis or treatment decisions.</p></div></footer></main>}

function Auth({mode,go}:{mode:'login'|'signup',go:(v:View)=>void}){const signup=mode==='signup';return <main className="grid min-h-screen place-items-center bg-[#f3f8f7] p-5"><div className="w-full max-w-md"><button onClick={()=>go('landing')} className="mb-7"><Logo/></button><div className="rounded-3xl border bg-white p-7 shadow-sm sm:p-9"><h1 className="text-2xl font-semibold">{signup?'Create your account':'Welcome back'}</h1><p className="mt-2 text-sm text-muted-foreground">{signup?'Set up a secure DrishtiAI workspace.':'Sign in to continue screening.'}</p><form className="mt-7 space-y-5" onSubmit={e=>{e.preventDefault();go('dashboard')}}>{signup&&<div><Label htmlFor="name">Full name</Label><Input id="name" required className="mt-2 h-11" placeholder="Dr. Asha Rao"/></div>}<div><Label htmlFor="email">Email address</Label><Input id="email" type="email" required className="mt-2 h-11" placeholder="you@clinic.org"/></div><div><Label htmlFor="password">Password</Label><Input id="password" type="password" required minLength={8} className="mt-2 h-11" placeholder="At least 8 characters"/></div>{signup&&<label className="flex gap-3 text-xs leading-5 text-muted-foreground"><input type="checkbox" required/> I agree to use demo outputs only as decision support and never as a definitive diagnosis.</label>}<Button className="h-11 w-full">{signup?'Create account':'Sign in'}</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">{signup?'Already have an account?':'New to DrishtiAI?'} <button className="font-medium text-primary" onClick={()=>go(signup?'login':'signup')}>{signup?'Sign in':'Create account'}</button></p></div><p className="mt-5 text-center text-xs text-muted-foreground">Demo authentication. Connect Supabase Auth for production.</p></div></main>}

function Shell({view,go,menu,setMenu,children}:{view:View,go:(v:View)=>void,menu:boolean,setMenu:(v:boolean)=>void,children:React.ReactNode}){const nav=[['dashboard',Home,'Overview'],['new',ScanLine,'New screening'],['history',History,'History'],['settings',Settings,'Settings']] as const;return <div className="min-h-screen bg-[#f7faf9]"><aside className={`fixed inset-y-0 left-0 z-30 w-64 border-r bg-white p-5 transition-transform lg:translate-x-0 ${menu?'translate-x-0':'-translate-x-full'}`}><div className="flex items-center justify-between"><Logo/><button className="lg:hidden" onClick={()=>setMenu(false)}><X/></button></div><nav className="mt-10 space-y-1">{nav.map(([v,I,label])=><button key={v} onClick={()=>go(v)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium ${view===v?'bg-secondary text-primary':'text-muted-foreground hover:bg-muted'}`}><I size={18}/>{label}</button>)}</nav><div className="absolute inset-x-5 bottom-5"><div className="mb-3 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-900"><strong>Demo mode</strong><br/>No validated model connected.</div><button onClick={()=>go('landing')} className="flex items-center gap-3 px-3 py-2 text-sm text-muted-foreground"><LogOut size={17}/> Sign out</button></div></aside>{menu&&<button className="fixed inset-0 z-20 bg-black/20 lg:hidden" onClick={()=>setMenu(false)}/>}<div className="lg:pl-64"><header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b bg-white/95 px-5 backdrop-blur lg:px-8"><button onClick={()=>setMenu(true)} className="lg:hidden"><Menu/></button><p className="hidden text-sm text-muted-foreground sm:block">Explainable retinal screening support</p><div className="flex items-center gap-3"><button className="grid size-9 place-items-center rounded-full bg-secondary text-primary"><HelpCircle size={17}/></button><span className="grid size-9 place-items-center rounded-full bg-primary text-sm font-semibold text-white">GA</span></div></header><main className="mx-auto max-w-6xl p-5 sm:p-8">{children}</main></div></div>}

function Dashboard({go}:{go:(v:View)=>void}){return <><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Monday, 31 August</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Good morning, Geetha</h1><p className="mt-2 text-muted-foreground">Here is your screening workspace at a glance.</p></div><Button className="h-11 rounded-xl" onClick={()=>go('new')}><ScanLine className="mr-2 size-4"/> New screening</Button></div><div className="mt-8 grid gap-4 sm:grid-cols-3">{[[Activity,'12','Screenings this week'],[Check,'8','Completed reviews'],[Clock3,'4 min','Average workflow']].map(([I,n,l])=>{const Icon=I as typeof Activity;return <div key={String(l)} className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><span className="grid size-10 place-items-center rounded-xl bg-secondary text-primary"><Icon size={19}/></span><span className="text-2xl font-semibold">{String(n)}</span></div><p className="mt-4 text-sm text-muted-foreground">{String(l)}</p></div>})}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1.6fr_1fr]"><section className="rounded-2xl border bg-white"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">Recent screenings</h2><p className="mt-1 text-sm text-muted-foreground">Latest demo analyses</p></div><button className="text-sm font-medium text-primary" onClick={()=>go('history')}>View all</button></div><ScreeningRows go={go}/></section><section className="rounded-2xl bg-primary p-6 text-primary-foreground"><span className="grid size-11 place-items-center rounded-xl bg-white/12"><FileImage/></span><h2 className="mt-6 text-xl font-semibold">Start a new review</h2><p className="mt-2 text-sm leading-6 text-white/75">Upload a retinal image and follow the guided quality and analysis workflow.</p><Button variant="secondary" className="mt-6" onClick={()=>go('new')}>Begin screening <ArrowRight className="ml-2 size-4"/></Button></section></div></>}

function ScreeningRows({go}:{go:(v:View)=>void}){return <div>{screenings.map(s=><button key={s.id} onClick={()=>go('details')} className="grid w-full grid-cols-[1fr_auto] items-center gap-4 border-b p-5 text-left last:border-0 hover:bg-muted/40 sm:grid-cols-[1.2fr_1fr_.7fr_auto]"><div><p className="text-sm font-medium">{s.id}</p><p className="mt-1 text-xs text-muted-foreground">{s.date}</p></div><p className="hidden text-sm sm:block">{s.grade}</p><Badge variant="secondary" className="hidden w-fit sm:inline-flex">{s.risk}</Badge><ChevronRight className="size-4 text-muted-foreground"/></button>)}</div>}

function NewScreening({go,choose,file,preview,error}:{go:(v:View)=>void,choose:(f?:File)=>void,file:File|null,preview:string,error:string}){return <div className="mx-auto max-w-3xl"><button onClick={()=>go('dashboard')} className="flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={16}/> Back to overview</button><div className="mt-7"><p className="eyebrow">New screening · Step 1 of 3</p><h1 className="mt-2 text-3xl font-semibold">Add a retinal image</h1><p className="mt-2 text-muted-foreground">Use a clear, centered fundus image in JPG or PNG format.</p></div><div className="mt-8 rounded-3xl border bg-white p-6 sm:p-8">{!file?<><label className="grid min-h-72 cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-primary/25 bg-[#f8fbfa] p-8 text-center hover:border-primary/50"><input className="sr-only" type="file" accept="image/jpeg,image/png" onChange={e=>choose(e.target.files?.[0])}/><span><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-secondary text-primary"><Upload/></span><strong className="mt-5 block">Drop an image here or browse</strong><span className="mt-2 block text-sm text-muted-foreground">JPG or PNG · Maximum 10 MB</span></span></label><div className="my-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>OR<span className="h-px flex-1 bg-border"/></div><Button variant="outline" className="w-full" onClick={()=>go('camera')}><Camera className="mr-2 size-4"/> Use camera capture</Button></>:<div><img src={preview} alt="Selected retinal image preview" className="mx-auto max-h-80 rounded-2xl bg-black object-contain"/><div className="mt-5 flex items-center justify-between rounded-xl bg-secondary p-4"><div><p className="text-sm font-medium">{file.name}</p><p className="mt-1 text-xs text-muted-foreground">{(file.size/1024/1024).toFixed(2)} MB · Ready for validation</p></div><button onClick={()=>choose(undefined)} className="text-sm text-primary">Change</button></div></div>}{error&&<Alert variant="destructive" className="mt-5"><Info/><AlertTitle>Image not accepted</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}<div className="mt-6 flex justify-end"><Button disabled={!file} onClick={()=>go('processing')}>Validate and analyze <ArrowRight className="ml-2 size-4"/></Button></div></div><Alert className="mt-5 bg-blue-50/60"><ShieldCheck/><AlertTitle>Privacy note</AlertTitle><AlertDescription>A production deployment should use private object storage, short-lived URLs, encryption, and an approved retention policy.</AlertDescription></Alert></div>}

function CameraCapture({go}:{go:(v:View)=>void}){const video=useRef<HTMLVideoElement>(null);const [state,setState]=useState<'idle'|'ready'|'denied'>('idle');const start=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(video.current)video.current.srcObject=stream;setState('ready')}catch{setState('denied')}};useEffect(()=>()=>{(video.current?.srcObject as MediaStream|null)?.getTracks().forEach(t=>t.stop())},[]);return <div className="mx-auto max-w-3xl"><button onClick={()=>go('new')} className="flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={16}/> Back to upload</button><h1 className="mt-7 text-3xl font-semibold">Camera capture</h1><p className="mt-2 text-muted-foreground">Align a retinal camera feed within the guide.</p><div className="mt-7 overflow-hidden rounded-3xl border bg-[#071411] p-4"><div className="relative grid aspect-[4/3] place-items-center overflow-hidden rounded-2xl bg-black"><video ref={video} autoPlay playsInline className="h-full w-full object-cover"/><div className="pointer-events-none absolute size-[58%] rounded-full border-2 border-dashed border-white/70"/>{state==='idle'&&<Button className="absolute" onClick={start}><Camera className="mr-2 size-4"/> Enable camera</Button>}{state==='denied'&&<p className="absolute max-w-sm rounded-xl bg-black/70 p-4 text-center text-sm text-white">Camera access was unavailable. Check browser permissions or return to image upload.</p>}</div><div className="mt-4 flex justify-center"><Button disabled={state!=='ready'} onClick={()=>go('processing')}>Capture image</Button></div></div></div>}

function Processing({go}:{go:(v:View)=>void}){const [p,setP]=useState(8);useEffect(()=>{const t=setInterval(()=>setP(x=>Math.min(x+14,100)),350);return()=>clearInterval(t)},[]);useEffect(()=>{if(p===100){const t=setTimeout(()=>go('result'),450);return()=>clearTimeout(t)}},[p,go]);const steps=[['Image validation',25],['Retina detection',48],['Demo inference',74],['Explanation map',95]];return <div className="mx-auto grid min-h-[70vh] max-w-xl place-items-center text-center"><div className="w-full"><span className="mx-auto grid size-20 place-items-center rounded-full bg-secondary text-primary"><ScanLine className="size-9 animate-pulse"/></span><p className="eyebrow mt-7">Demo analysis in progress</p><h1 className="mt-2 text-3xl font-semibold">Reviewing the image</h1><p className="mt-3 text-muted-foreground">This simulated pipeline demonstrates how a validated model can be integrated.</p><Progress value={p} className="mt-8 h-2"/><div className="mt-7 space-y-3 text-left">{steps.map(([s,n])=><div key={s} className="flex items-center justify-between rounded-xl border bg-white p-4 text-sm"><span>{s}</span>{p>=Number(n)?<Check className="size-4 text-primary"/>:<span className="text-muted-foreground">Waiting</span>}</div>)}</div></div></div>}

function Result({go,preview}:{go:(v:View)=>void,preview:string}){return <div><button onClick={()=>go('dashboard')} className="flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={16}/> Back to overview</button><div className="mt-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge className="bg-amber-100 text-amber-900 hover:bg-amber-100">Simulated demo result</Badge><h1 className="mt-3 text-3xl font-semibold">Screening result</h1><p className="mt-2 text-sm text-muted-foreground">DRS-240831-03 · 31 Aug 2026, 10:24</p></div><Button variant="outline" onClick={()=>window.print()}>Print summary</Button></div><Alert className="mt-6 border-amber-200 bg-amber-50"><Info className="text-amber-700"/><AlertTitle>Not a clinical prediction</AlertTitle><AlertDescription>No trained or validated model is connected. The values below are fixed demo content for interface testing only.</AlertDescription></Alert><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.15fr]"><section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Image review</h2><div className="relative mt-4 grid aspect-square place-items-center overflow-hidden rounded-2xl bg-[#100c0e]">{preview?<img src={preview} alt="Uploaded retinal image" className="h-full w-full object-contain"/>:<div className="size-[78%] rounded-full bg-[radial-gradient(circle_at_44%_42%,#f9b267_0,#9d392e_17%,#501719_45%,#180c10_68%)]"/>}<span className="absolute left-[38%] top-[35%] size-20 rounded-full border-2 border-amber-300 bg-amber-300/15"/><span className="absolute left-[56%] top-[53%] size-12 rounded-full border-2 border-amber-300 bg-amber-300/15"/></div><div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><span className="size-3 rounded-full border border-amber-500 bg-amber-300/20"/> Demo attention regions (illustrative)</div></section><ResultCard/></div><section className="mt-6 rounded-2xl border bg-white p-6"><h2 className="font-semibold">Recommended next step</h2><p className="mt-3 leading-7 text-muted-foreground">Because this demo shows an elevated-risk pattern, the illustrative guidance is to arrange review by a qualified eye-care professional. Urgent symptoms should receive prompt clinical evaluation regardless of this screen.</p><div className="mt-5 flex flex-wrap gap-3"><Button onClick={()=>go('new')}>Start another screening</Button><Button variant="outline" onClick={()=>go('history')}>View history</Button></div></section><p className="mt-6 text-xs leading-5 text-muted-foreground"><strong>Medical disclaimer:</strong> DrishtiAI is a screening and decision-support demonstration. It does not provide a diagnosis, replace a comprehensive eye examination, or determine treatment.</p></div>}

function ResultCard({compact=false}:{compact?:boolean}){return <div className={`rounded-2xl border bg-white ${compact?'p-5 sm:p-7':'p-6'}`}><div className="flex items-center justify-between"><div><p className="eyebrow">Demo classification</p><h2 className="mt-2 text-xl font-semibold">Moderate NPDR</h2></div><span className="grid size-11 place-items-center rounded-full bg-amber-100 text-amber-800"><Activity/></span></div><div className="mt-7 grid grid-cols-2 gap-4"><div className="rounded-xl bg-muted p-4"><p className="text-xs text-muted-foreground">Confidence</p><p className="mt-1 text-2xl font-semibold">87%</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs text-amber-800">Risk level</p><p className="mt-1 font-semibold text-amber-900">Elevated</p></div></div><div className="mt-6"><div className="mb-2 flex justify-between text-sm"><span>Class confidence</span><span>87%</span></div><Progress value={87}/></div><div className="mt-6 rounded-xl border border-dashed border-primary/30 bg-[#f8fbfa] p-4 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Plain-language explanation</strong><br/>The demo highlights retinal regions that would contribute to the model output. A validated implementation should use calibrated probabilities and a clinically reviewed explanation method such as Grad-CAM.</div>{compact&&<p className="mt-4 text-center text-xs text-muted-foreground">Illustrative output only. No validated model connected.</p>}</div>}

function HistoryPage({go}:{go:(v:View)=>void}){return <div><p className="eyebrow">Screening records</p><h1 className="mt-2 text-3xl font-semibold">History</h1><p className="mt-2 text-muted-foreground">Review previous demo screening records.</p><div className="mt-7 flex gap-3"><Input aria-label="Search screenings" placeholder="Search by screening ID" className="max-w-sm bg-white"/><Button variant="outline">Filter</Button></div><section className="mt-5 overflow-hidden rounded-2xl border bg-white"><ScreeningRows go={go}/></section></div>}

function SettingsPage(){return <div className="max-w-3xl"><p className="eyebrow">Account</p><h1 className="mt-2 text-3xl font-semibold">Profile & settings</h1><section className="mt-7 rounded-2xl border bg-white p-6"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-full bg-secondary text-primary"><User/></span><div><h2 className="font-semibold">Geetha</h2><p className="text-sm text-muted-foreground">Demo workspace user</p></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><div><Label htmlFor="sname">Display name</Label><Input id="sname" defaultValue="Geetha" className="mt-2"/></div><div><Label htmlFor="org">Organization</Label><Input id="org" placeholder="Clinic or institution" className="mt-2"/></div></div><Button className="mt-6">Save changes</Button></section><section className="mt-5 rounded-2xl border bg-white p-6"><h2 className="font-semibold">Data & privacy</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Configure retention, consent, access logging, and storage policies before handling real health data. Demo mode stores no data on the server.</p></section></div>}
